# Generated by Django 5.0.2 on 2025-03-23 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='timings',
            field=models.CharField(default='Not Available', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
