# Generated by Django 5.0.2 on 2025-03-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0011_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpatient',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='pat_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='spec_id',
            new_name='spec',
        ),
        migrations.RenameField(
            model_name='doctorreg',
            old_name='specialization_id',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='pat_id',
            new_name='patient',
        ),
        migrations.AlterModelTable(
            name='day',
            table='dasapp_day',
        ),
    ]
