# Generated by Django 5.0.2 on 2025-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0012_rename_doctor_id_addpatient_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpatient',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='pat_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='spec',
            new_name='spec_id',
        ),
        migrations.RenameField(
            model_name='doctorreg',
            old_name='specialization',
            new_name='specialization_id',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='patient',
            new_name='pat_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin')], default=1, max_length=50),
        ),
        migrations.AlterModelTable(
            name='day',
            table=None,
        ),
    ]
